- hosts: "*"
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'
        autoremove: true



    - name: Update flatpak if available
        command: flatpak update -y
        register: flatpak_result
        failed_when: false
        changed_when: "'Nothing to do.' not in flatpak_result.stdout"  
