---
- name: Deploy Jellyfin Docker Container with Env Variables
  hosts: m2
  become: true

  tasks:
    - name: Clone Jellyfin Docker Compose from GitHub
      git:
        repo: https://github.com/n0access/dockers.git
        dest: /home/ken/docker/jellyfin-docker
      register: git_clone
